apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingtalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dingtalk
  template:
    metadata:
      labels:
        app: dingtalk
    spec:
      containers:
        image: zhuqiyang/dingtalk:1.0
        imagePullPolicy: IfNotPresent
        name: dingtalk
        ports:
        - name: dingtalk
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dingtalk
spec:
  selector:
    app: dingtalk
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    targetPort: 80
